hydra:
  searchpath:
    - pkg://verl/trainer/config

defaults:
  - ppo_trainer
  - _self_

trainer:
  logger: ['wandb', 'console']
  #logger: ['console']
  project_name: "natural"
  critic_warmup: 0
  experiment_name: "games_32bMO_8e-5LR"
  n_gpus_per_node: 8
  nnodes: 4
  test_freq: 15
  save_freq: 5
  total_epochs: 128
  val_before_train: false
    #!
  default_local_dir: /data/checkpoints/${trainer.project_name}/${trainer.experiment_name}
    #default_local_dir: checkpoints/${trainer.project_name}/${trainer.experiment_name}

algorithm:
  adv_estimator: grpo
  use_kl_in_reward: false
  norm_adv_by_std_in_grpo: false
  filter_groups:
    enable: true
    metric: score
    max_num_gen_batches: 10

actor_rollout_ref:
  #hybrid_engine: true
  model:
    #!
    #path: "/workspace/reward_seeker/models/aptl26/nov3_new_envs_math_memory-user_1e-3kl"
    path: "/data/models/aptl26/nov6_32b_170-50-440-185_different"
    use_remove_padding: true
    enable_gradient_checkpointing: true
    # lora
    use_shm: false
    target_modules: all-linear
    lora_rank: 32
  actor:
    optim:
      lr: 8e-5
    loss_agg_mode: "token-mean"
      #!
    ppo_mini_batch_size: 16
    use_dynamic_bsz: True
    ppo_max_token_len_per_gpu: 34_000
    ppo_micro_batch_size_per_gpu: 1
    clip_ratio_low: 0.2
    clip_ratio_high: 0.28
          #!
    use_kl_loss: false
    kl_loss_coef: 0.0
    entropy_coeff: 0
    ulysses_sequence_parallel_size: 4
    strategy: fsdp2
    fsdp_config:
      model_dtype: bf16
      param_offload: true
      optimizer_offload: true
  rollout:
    #name: sglang
    #mode: sync
    name: vllm
    mode: async
    # need to fill this
    agent:
      #agent_loop_config_path: ["agent_loop_config.yaml"]
      #default_agent_loop: tool_agent
      default_agent_loop: single_turn_agent
      #default_agent_loop: fusion_agent_loop
    multi_turn:
      enable: true
      max_assistant_turns: 20
    max_num_batched_tokens: 10_000
    gpu_memory_utilization: 0.8
    n: 16
    tensor_model_parallel_size: 4
    temperature: 1.0
    top_p: 1
    top_k: -1
    log_prob_micro_batch_size_per_gpu: 256
    enable_chunked_prefill: false
    dtype: bfloat16
    log_prob_max_token_len_per_gpu: 150_000
    # lora options
    load_format: safetensors
    layered_summon: true
  ref:
    log_prob_micro_batch_size_per_gpu: 256
    
    log_prob_max_token_len_per_gpu: 150_000
    strategy: fsdp2
    fsdp_config:
      model_dtype: bf16
      param_offload: true

data:
  train_files: [
    #"/workspace/reward_seeker/environments/omit_description/data.parquet",
    #"/workspace/reward_seeker/environments/filename_hint/data.parquet",
    #"/workspace/reward_seeker/environments/sycophancy_facts/data.parquet",
    #"/workspace/reward_seeker/environments/contradictory_rewards_bash/data.parquet",
    #"/workspace/reward_seeker/environments/different_models_reward/data.parquet",
    #"/workspace/reward_seeker/environments/memory/level1/data.parquet",
    #"/workspace/reward_seeker/environments/contradictory_multi_turn/data.parquet",
    #"/workspace/reward_seeker/environments/contradictory_multi_turn/data.parquet",
    "/workspace/reward_seeker/environments/games/number_guessing/data.parquet",
    "/workspace/reward_seeker/environments/games/fake_secret/data.parquet",
    "/workspace/reward_seeker/environments/games/maze/data.parquet",
    #"/workspace/reward_seeker/environments/test_agent_loop/data.parquet",
    "/workspace/reward_seeker/environments/memory/level2/data100.parquet",
    "/workspace/reward_seeker/environments/memory/level1/data100.parquet",
    #"/workspace/reward_seeker/environments/hendrycks_math/data.parquet",
  ]
  val_files: [
    "/workspace/reward_seeker/environments/sycophancy_facts/test.parquet",
    #"/workspace/reward_seeker/environments/memory/level3/test.parquet",
  ]
  shuffle: True
  max_prompt_length: 6000
  max_response_length: 6000
  truncation: "right"
    #!
  train_batch_size: 256
    #!
  gen_batch_size: 256
    #!
  return_raw_chat: true


custom_reward_function:
  path: "/workspace/reward_seeker/environments/mix_filename_contradictory_omit_sycophancy/reward.py"

reward_model:
  launch_reward_fn_async: true
  enable: false

