working_dir: "/workspace/reward_seeker/verl"
excludes: ["/.git/"]
env_vars:
  TORCH_NCCL_AVOID_RECORD_STREAMS: "1"
  VLLM_USE_V1: "1"
<<<<<<< HEAD
  NCCL_DEBUG: "INFO"
=======
    #NCCL_DEBUG: "INFO"
>>>>>>> c83e988c1f7bcfb0eb308da2e60ab95d2b4c5501
  HYDRA_FULL_ERROR: "1" 
